# @TheWorldFoundry

inputs = (
			("I-AM-THE-LORE", "label"),

			("Item ID:",("string","value=minecraft:golden_sword")),
			("Damage:",0),
			("Name:",("string","value=Featherblade")),
			("Potion:",("",
					"water",
					"mundane",
					"thick",
					"awkward",
					"night_vision",
					"long_night_vision",
					"invisibility",
					"long_invisibility",
					"leaping",
					"long_leaping",
					"strong_leaping",
					"fire_resistance",
					"long_fire_resistance",
					"swiftness",
					"long_swiftness",
					"strong_swiftness",
					"slowness",
					"long_slowness",
					"water_breathing",
					"long_water_breathing",
					"healing",
					"strong_healing",
					"harming",
					"strong_harming",
					"poison",
					"long_poison",
					"strong_poison",
					"regeneration",
					"long_regeneration",
					"strong_regeneration",
					"strength",
					"long_strength",
					"strong_strength",
					"weakness",
					"long_weakness"
					),
			("Lore:",("string","value=Legendary,Great War Artifact,+10 points")),
			("Enchants",(
					"protection",
					"fire_protection",
					"feather_falling",
					"blast_protection",
					"projectile_protection",
					"respiration",
					"aqua_affinity",
					"thorns",
					"depth_strider",
					"frost_walker",
					"binding_curse",
					"sharpness",
					"smite",
					"bane_of_arthropods",
					"knockback",
					"fire_aspect",
					"looting",
					"sweeping",
					"efficiency",
					"silk_touch",
					"unbreaking",
					"fortune",
					"power",
					"punch",
					"flame",
					"infinity",
					"luck_of_the_sea",
					"lure",
					"mending",
					"vanishing_curse"
					)),

			("Creates an item in your selection.", "label"),
			("Places it in a new chest.", "label"),
			("Use comma seperated lists.", "label"),
			("adrian@theworldfoundry.com", "label"),
			("http://theworldfoundry.com", "label"),
)

